import { StockData } from "@/types/StockData";
import { allItems } from "./allItems";

export const pickle: StockData = {
  allItems,
  currentStock: 60,
  days: [
    {
      type: "Actual",
      formattedDate: "SEP 3rd, 2022",
      stock: 52.2,
      demand: 21,
      formattedWeekDay: "Sun",
    },
    {
      type: "Actual",
      formattedDate: "SEP 4th, 2022",
      stock: 43,
      demand: 16,
      formattedWeekDay: "Mon",
    },
    {
      type: "Actual",
      formattedDate: "SEP 5th, 2022",
      stock: 35,
      demand: 11,
      formattedWeekDay: "Tue",
    },
    {
      type: "Today",
      formattedDate: "SEP 6rd, 2022",
      stock: 25,
      demand: 9,
      formattedWeekDay: "Wed",
    },
    {
      type: "Projected",
      formattedDate: "SEP 7th, 2022",
      stock: 19,
      demand: 11,
      formattedWeekDay: "Thu",
    },
    {
      type: "Projected",
      formattedDate: "SEP 8th, 2022",
      stock: 16,
      demand: 9,
      formattedWeekDay: "Fri",
    },
    {
      type: "Projected",
      formattedDate: "SEP 9th, 2022",
      stock: 6,
      demand: 3.5,
      formattedWeekDay: "Sat",
    },
    {
      type: "Projected",
      formattedDate: "SEP 10th, 2022",
      stock: 53,
      demand: 19,
      formattedWeekDay: "Sun",
    },
    {
      type: "Projected",
      formattedDate: "SEP 11th, 2022",
      stock: 32,
      demand: 12,
      formattedWeekDay: "Mon",
    },
    {
      type: "Projected",
      formattedDate: "SEP 12th, 2022",
      stock: 26,
      demand: 19,
      formattedWeekDay: "Tue",
    },
    {
      type: "Projected",
      formattedDate: "SEP 13th, 2022",
      stock: 15,
      demand: 10,
      formattedWeekDay: "Wed",
    },
    {
      type: "Projected",
      formattedDate: "SEP 14th, 2022",
      stock: 12,
      demand: 7,
      formattedWeekDay: "Thu",
    },
    {
      type: "Projected",
      formattedDate: "SEP 15th, 2022",
      stock: 6,
      demand: 3,
      formattedWeekDay: "Fri",
    },
    {
      type: "Projected",
      formattedDate: "SEP 16th, 2022",
      stock: 4,
      demand: 2,
      formattedWeekDay: "Sat",
    },
  ],
  highestValue: 52.2,
  itemId: "1234",
  itemIcon: {
    alt: "Pickle icon",
    src: "/Pickle.svg",
  },
  itemName: "Pickle",
  lowestValue: 9,
  maximumStock: 150,
  slug: "pickle",
  unitOfMeasurement: "kg",
};
